{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Endpoint Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "endPointLatency_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Endpoint Latency"
    }
   ]
  },
  {
   "title": "Auth Successes vs Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(authSuccess_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Successes"
    },
    {
     "expr": "rate(authFail_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "Fails"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizzaLatency_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza Creation Latency"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(methods_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{method}}"
    },
    {
     "expr": "sum(rate(methods_total{source=\"jwt-pizza-service\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Requests By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[$__rate_interval])",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Total Profit - Bitcoin",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pizzaSales_total{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza's Created and Failed per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(pizzaCreation_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Creation Success"
    },
    {
     "expr": "rate(pizzaFailed_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza Creation Failed"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "numberOfUsers_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Number of Users"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuTemp_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memoryUsage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}